/*
file : ID_demoroom.h
*/

#ifndef _YB_DEMO_ROOM_ID_H_
#define _YB_DEMO_ROOM_ID_H_

#define ID_DEMO_ROOM_BACKGROUND				101

#define ID_DEMO_ROOM_READYBUTTON			102
#define ID_DEMO_ROOM_STARTBUTTON			103

#define ID_DEMO_ROOM_REDTEAM				104
#define ID_DEMO_ROOM_BLUETEAM				105

#define ID_DEMO_ROOM_MAPLEFT				106
#define ID_DEMO_ROOM_MAPRIGHT				107

#define ID_DEMO_ROOM_GRAYSLOTSTART			111
#define ID_DEMO_ROOM_REDSLOTSTART			121
#define ID_DEMO_ROOM_BLUESLOTSTART			131
#define ID_DEMO_ROOM_READYFLAGSTART			141
#define ID_DEMO_ROOM_USERNAMESTART			161
#define ID_DEMO_ROOM_CROWNSTART				181
#define ID_DEMO_ROOM_SLOTCOUNT				8

#define ID_DEMO_ROOM_MINIMAPSTART			151
#define ID_DEMO_ROOM_MINIMAPCOUNT			6

#define ID_DEMO_ROOM_MINIMAPNAME			171


#endif // _YB_DEMO_ROOM_ID_H_